name: Auto-generate sitemap

# <-- Give the built-in GITHUB_TOKEN permission to write files
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate sitemap
        run: python generate_sitemap.py

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml"
          git push